// Generated by gencpp from file pi_face_tracker/Face.msg
// DO NOT EDIT!


#ifndef PI_FACE_TRACKER_MESSAGE_FACE_H
#define PI_FACE_TRACKER_MESSAGE_FACE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace pi_face_tracker
{
template <class ContainerAllocator>
struct Face_
{
  typedef Face_<ContainerAllocator> Type;

  Face_()
    : id(0)
    , point()
    , attention(0.0)  {
    }
  Face_(const ContainerAllocator& _alloc)
    : id(0)
    , point(_alloc)
    , attention(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef float _attention_type;
  _attention_type attention;





  typedef boost::shared_ptr< ::pi_face_tracker::Face_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pi_face_tracker::Face_<ContainerAllocator> const> ConstPtr;

}; // struct Face_

typedef ::pi_face_tracker::Face_<std::allocator<void> > Face;

typedef boost::shared_ptr< ::pi_face_tracker::Face > FacePtr;
typedef boost::shared_ptr< ::pi_face_tracker::Face const> FaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pi_face_tracker::Face_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pi_face_tracker::Face_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pi_face_tracker::Face_<ContainerAllocator1> & lhs, const ::pi_face_tracker::Face_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.point == rhs.point &&
    lhs.attention == rhs.attention;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pi_face_tracker::Face_<ContainerAllocator1> & lhs, const ::pi_face_tracker::Face_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pi_face_tracker

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pi_face_tracker::Face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_face_tracker::Face_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pi_face_tracker::Face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pi_face_tracker::Face_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_face_tracker::Face_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_face_tracker::Face_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pi_face_tracker::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e50a53ae9f2ade62039cc5bdc75e8c3";
  }

  static const char* value(const ::pi_face_tracker::Face_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e50a53ae9f2ade6ULL;
  static const uint64_t static_value2 = 0x2039cc5bdc75e8c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::pi_face_tracker::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pi_face_tracker/Face";
  }

  static const char* value(const ::pi_face_tracker::Face_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pi_face_tracker::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Face in 3D space\n"
"int32 id\n"
"geometry_msgs/Point point\n"
"float32 attention\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::pi_face_tracker::Face_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pi_face_tracker::Face_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.point);
      stream.next(m.attention);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Face_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pi_face_tracker::Face_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pi_face_tracker::Face_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "attention: ";
    Printer<float>::stream(s, indent + "  ", v.attention);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PI_FACE_TRACKER_MESSAGE_FACE_H
